### PR TITLE
Add support for inline Math

### PR DESCRIPTION
**Pull request by leonsim**
For me, it's very convenient to write LaTex by inline. With MathJax, I can achieve this. I added this feature one year ago, and it has been working well on my own blog.

According to this bolg <http://www.eyeshalfclosed.com/blog/2013/07/29/which-markdown/>. I realize that there might be other people besides me who consider embedded LaTex important, so I submit this pull request.

I just capture text between `\(` and `\)`, and pass them to output without further processing.

### CODE REVIEW

**Comment by snnn** [comment]
Hi @leonsim , How about $$ ?

**Comment by Orc** [comment]
Okay, I'm getting to this late and I'm sorry.   But this \( ... \) patch is just a way to pass raw-except-for-`cputc()`-transforms code to the compiled output, yes?

**Comment by leonsim** [comment]
@snnn `$$` is too easy to conflict with normal text, so I would recommend the `\(` and `\)` way.

**Comment by leonsim** [comment]
@Orc Yes.

**Comment by Orc** [comment]
I'm going to pull your changes in  (assuming I can remember how to collapse branches after I finish testing everything out :-), but wrappered with the `configure.sh` option `--with-latex` so that to have latex it's gotta be built that way.

**Comment by leonsim** [comment]
@Orc Thank you.

**Comment by Orc** [comment]
Pulled, tweaked, tested, merged.   Thanks!

**Comment by snnn** [comment]
Hi @leonsim  and @Orc ,

This patch is incomplete.

There are two latex modes in mathjax:

1.  inline mode. started by \(, ended by \)
2.  block mode. started by $$, ended by $$. 

These delimiters are configurable. If you feel $$ is too common to conflict with normal text, you can use other char sequences.

The problem is:  it should either support both of these modes, or none.  For equations in a single document, they should be written in a **consistent** way.  

stackoverflow is a good example how latex works in web. for more information, see [this help](http://math.stackexchange.com/help/notation)

BTW, for markdown, it would better if the latex equations were html encoded before be passed to the output. So we can write \\( 1 < 2 \\) instead of \\(1 &amp;lt; 2 \\)

**Comment by leonsim** [comment]
@snnn This pull request is only for inline mode as described in the title of the pull request.  I misunderstood your meaning in my previous comment. I thought you meant the `$` delimiter for inline mode. 
For the block mode, it's more complicated. When I use block mode, I just write a equation in a single paragraph with inline mode. Does this way satisfy your requirements?
Of course you can just write \( 1 < 2 \) because MathJax will handle all this for you.

**Comment by snnn** [comment]
Hi @leonsim ,

I know your pull request is only for inline mode, but the user do not know that. All they know is discount added latex support, but, they have to write **x_1** for inline math, and **x\\\_1** for block math and **x\\\_1** for both inline and block math if they didn't turn on the latex option on build.

> When I use block mode, I just write a equation in a single paragraph with inline mode. Does this way satisfy your requirements?

No. The result picture are very different. Please try this formula in your browser:
\sum\_{i=1}^n i 

> Of course you can just write ( 1 < 2 ) because MathJax will handle all this for you.

Sorry I didn't describe the problem correctly.  It is:
_( 1<2 \) instead of \(1&amp;lt;2 \)_
without spaces around the operator.

**Comment by Orc** [comment]
So basically there's no standard way to embed tex in other documents and everybody does their own thing in their own way?

That's, um, not useful or even appropriate for me to try to support in discount.

**Comment by leonsim** [comment]
@snnn I want to make sure, we are both talking the MathJax standard?

**Comment by leonsim** [comment]
@snnn You're right about block mode. It looks different. Adding block mode support is similar to inline mode. I can add it in another pull request if @Orc agrees.

@snnn `\( 1<2 \)` is also supported directly by MathJax.

@Orc Assuming snnn also means the MathJax standard, we got one as described at MathJax`s official [website](https://docs.mathjax.org/en/v2.6-latest/start.html): 
> The default math delimiters are $$...$$ and \[...\] for displayed mathematics, and \(...\) for in-line mathematics. Note in particular that the $...$ in-line delimiters are not used by default.

**Comment by Orc** [comment]
Ok.  So there are 3 sets of delimiters ('$$', '\[', '\(') and as far as the markdown engine cares all it has to do is pass those delimiters and their enclosed text almost-verbatim to the output?

That should be pretty easy to handle;  you don't need to add another pull request, I'll just whip it up right now as an excuse to put off finishing the handlebar bag I'm working ot.

**Comment by leonsim** [comment]
@Orc 

> So there are 3 sets of delimiters ('$$', '[', '(') and as far as the markdown engine cares all it has to do is pass those delimiters and their enclosed text almost-verbatim to the output?

Yes

That would be awesome. Thank you.

**Comment by Orc** [comment]
Pushed.  The mathhandler code is not as nice as it should be, so I may revisit it in the future.

**Comment by leonsim** [comment]
@snnn I reviewed the code, and actually for the `\( 1<2 \)` case, it is html encoded before be passed to the output. Please check the code.

**Comment by Orc** [comment]
Is the text between the magic latex delimiters supposed to be html encoded or not?

**Comment by leonsim** [comment]
@Orc Yes it is. @snnn is right.

According to MathJax's official website:

> Usually, it is sufficient to simply put spaces around these symbols to cause the browser to avoid them, so
> 
> ... when `\(x < y\)` we have ...
> should work. Alternatively, you can use the HTML entities &lt;, &gt; and &amp; to encode these characters so that the browser will not interpret them, but MathJax will. E.g.,
> 
> ... when `\(x &lt; y\)` we have ...
>

**Pull request closed without merging**
