### PR TITLE
Remove tabs from test cases to make them work

### PR DESCRIPTION
**Pull request by ghedo**
They would otherwise fail.

### CODE REVIEW

**Comment by Orc** [comment]
How are the test cases failing?

As a general rule, my reaction to a test case failing is not to change the test case, but to see what changed in discount to make it start failing.

**Comment by ghedo** [comment]
This is the errors I get:
```
data corruption cases from Fernando Muñoz ............
id_000040_06
source:
	<dl></d
		>00000
diff:
	2c2
	<         >00000</p>
	---
	>     >00000</p>

id_000152_06
source:
	<p></
		>00000
diff:
	2c2
	<         >00000</p>
	---
	>     >00000</p>

id_000163_06
source:
	<div></di
		>00000
diff:
	2c2
	<         >00000</p>
	---
	>     >00000</p>

id_000167_06
source:
	<div </di
		>00000
diff:
	2c2
	<         >00000</p>
	---
	>     >00000</p>

id_000223_06
source:
	<!--
		-->00000
diff:
	2c2
	<         -->00000</p>
	---
	>     -->00000</p>

tests/muñoz.t: 70 tests; 5 failed/65 passed

Makefile:106: recipe for target 'test' failed
make: *** [test] Error 1
```

maybe the tabs are interpreted differently?

**Comment by Orc** [comment]
How did you configure your version of discount when you built it?

**Comment by ghedo** [comment]
I can reproduce by just running `configure.sh` without  any arguments.

**Comment by Orc** [comment]
Okay, that's bizarre;  I built discount w/o any arguments and couldn't reproduce the failure.

Does it *not* fail for you when you configure --with-tabstops ?

**Comment by Orc** [comment]
Okay, oddness;  there's a dependency failure in the build;  I *don't* reproduce the failure if I ./configure.sh;make test, but I *do* if I make distclean;./configure.sh;make test.

**Pull request merged**
