### PR TITLE
Add `extern "C"` to use from C++

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by Orc** [comment]
I don't want to clutter the header file with c++-specific things (yes, I know that it's ignored because of the #ifdefs, but eww it's kind of ugly) but I did make a c++ wrapper class for it @ https://gist.github.com/Orc/97b5711dd8c8a3b371928db756eba6e5 that gives a c++ wrappered interface to the c methods plus a little c++ class for it.

Can you look at the gist and see if that will do it for you?

**Comment by podsvirov** [comment]
Please open the  `stdio.h` header file and you will see:

    #ifdef __cplusplus
    extern "C" {
    #endif

I believe that C and C ++ are good friends :-) !

What about https://gist.github.com/Orc/97b5711dd8c8a3b371928db756eba6e5 - now it's ugly for usage from C++ (although, this is my personal opinion).

Please merge this small change.

**Comment by Orc** [comment]
Yes, but I'm not the one who's maintaining stdio.h :-)

Let me think about it for a while.

**Comment by podsvirov** [comment]
I apologize for persistence. I dutifully await your decision.

PS: I would not want to lose the ability to use the original interface.

**Comment by Orc** [comment]
Not a problem!   Note that even in the case of mkdio.h++ the original interface is still exposed at the c++ level, because I simply wrapped the class around it.

**Comment by podsvirov** [comment]
Ok. It's working from C++ without this changes. In C++ we need wrap `#include <mkdio.h>` to `extern "C" { ... }` scope.

```cpp
// main.cpp
#include <iostream>
extern "C" {
#include <mkdio.h>
}
int main()
{
    std::string text = "Hello **DISCOUNT**!";
    std::cout << "TEXT: " << text << std::endl;
    mkd_flag_t flag = MKD_1_COMPAT;
    MMIOT *doc = mkd_string(text.c_str(), text.size(), flag);
    if (!mkd_compile(doc, flag)) {
        std::cerr << "Markdown Compilation Error!" << std::endl;
        mkd_cleanup(doc);
        return 1;
    }
    char *res = nullptr;
    int size = mkd_document(doc, &res);
    if (size) {
        std::string html(res, res + size);
        std::cout << "HTML: " << html << std::endl;
    }
    mkd_cleanup(doc);
    return 0;
}
```

Output:

```
> TEXT: Hello **DISCOUNT**!
> HTML: <p>Hello <strong>DISCOUNT</strong>!</p>
```

**Comment by imikejackson** [comment]
Another option would be to have CMake generate a discount.hpp file that just has:

    extern "C" {
      #include "mkdio.h"
    }

and then add an install rule to install the header when "make install" is issued. That would keep the original sources clean like the author prefers.

**Comment by podsvirov** [comment]
Good idea, but there is one minus. This only works for one build system.

**Comment by Orc** [comment]
I don't understand what you mean by "only one build system"?   A header file is a header file, yes?

**Comment by podsvirov** [comment]
This means that the header file will be available to users only if built and installed using CMake.

**Comment by podsvirov** [comment]
We can also add header `mkdio.hpp` with similar content to sources and install the via autotools and CMake.

**Comment by Orc** [comment]
No, if I did that approach I'd stuff the installation into the regular Makefile;  remember that I don't use Cmake at all!

**Comment by Orc** [comment]
Okay, a compromise solution has been implemented:   if `configure.sh` is given the `--cxx-binding` option, it generates a mkdio.h file that's got the `extern "C" {` ... `}`' wrapper on it, otherwise it simply generates the traditional C-only interface.   This means that your patch can't be used (well, it *can*, it just would double up the `extern "C" {` ... `}` wrapper) but as long as you remember to configure with `--cxx-binding` this will work, yes?)

(tested locally from C, plus the _extremely trivial_ C++ program of :

````
#include <stdio.h>
#include "mkdio.h"

int main(int argc, char **argv)
{
    printf("markdown_version: %s\n", markdown_version);
}
````

**Pull request closed without merging**
