### PR TITLE
#124: Convert much compiletime configuration to runtime flags

### PR DESCRIPTION
**Pull request by binki**
See issue #124.

I generated a lot of changesets because I converted each configurable item independently to avoid confusing myself.

I also added `.gitignore` and `.dir-locals.el` to make working with the code easier for me. I hope you don’t mind—you’re actually using sccs instead of git yourself? :-p

The change I’m most concerned about is the code fencing one as that didn’t translate directly from `#if` into `if ()`, if you see what I mean regarding the `switch ()` in `markdown.c`. I think I got the logic right, though maybe you have a better way to lay it out or want to simplify it somehow with a macro.

### CODE REVIEW

**Comment by Orc** [comment]
I like all of your changes _except_ for the `.gitignore` and `.dir-locals.el` -- I hate cluttering up my baseline with miscellaneous files.   Could you split those two out into a separate changeset?

**Comment by binki** [comment]
OK, I pulled those commits out.

**Comment by Orc** [comment]
Danka, and merged!

**Comment by binki** [comment]
Thanks!

**Pull request merged**
