### PR TITLE
Ignore build output.

### PR DESCRIPTION
**Pull request by bradleysepos**
Especially helpful where discount is a git submodule of another project.

### CODE REVIEW

**Comment by Orc** [comment]
As much as it's nice to make git stfu, a gitignore file isn't really related to the codebase, so I'm not going to take this one.  Sorry!

**Comment by bradleysepos** [comment]
Why not go all the way? `rm -rf .git` :octocat: :smile:

**Comment by Orc** [comment]
There would be much wailing an gnashing of teeth if I reverted my version control to SCCS :-)

**Comment by binki** [comment]
Aww

**Pull request closed without merging**
