### PR TITLE
Add more tests for latex support for block mode.

### PR DESCRIPTION
**Pull request by leonsim**
Tests for issue https://github.com/Orc/discount/pull/127

### CODE REVIEW

**Comment by Orc** [comment]
The tests weren't right?

**Comment by leonsim** [comment]
@Orc They are right, just not complete.

**Comment by leonsim** [comment]
@Orc Please note one test failed. This shows there may be a bug for the `$$` delimiter.

**Comment by Orc** [comment]
Which test fails?

**Comment by leonsim** [comment]
@Orc 
```
source:
	$[a](b)$
diff:
	1c1
	< <p>$<a href="b">a</a>$</p>
	---
	> <p>$[a](b)$?</p>

```

**Comment by Orc** [comment]
Ah, that's a defect in the code i wrote for matching $$ -- i will fix it tomorroe

**Comment by Orc** [comment]
s/tomorroe/tomorrow/

Stupid iphone.

**Comment by leonsim** [comment]
Sure :smile:

**Pull request merged**
