### PR TITLE
Remove redundant <unistd.h> header as unused

### PR DESCRIPTION
**Pull request by mloskot**
This enables compilation of `main.c` and `makepage.c` with VC++

### CODE REVIEW

**Comment by Orc** [comment]
(my same bemused comment about pgm_options.c applies here :-)

**Comment by mloskot** [comment]
I guess :-)

**Comment by Orc** [comment]
Okay, I needed to back that one out in a hurry because it broke the builds on all of my machines.   On most unices, unistd.h is where the externals for getopt are found.

**Comment by mloskot** [comment]
Ups, I'm sorry!
Apparently, I got lazy relying on Travis CI which is not enabled for Discount.

Can we solve it this way?


```
/* config.h */
#define HAVE_UNISTD_H 1
```

then

```
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
```

**Comment by Orc** [comment]
Maybe.  Let me think about it for a bit;  I'd probably want to put a test for it into configure.sh and put the #include for unistd.h there if I don't use it for anything else (which I don't, I don't think)

**Comment by Orc** [comment]
But in your case just not pulling in the reversion patch will work for now

**Comment by Orc** [comment]
What are you using for a getopt?  A handmade third-party one or does it exist but is not actually documented in the VC++ libraries?

**Comment by mloskot** [comment]
I gave up on building Discount executables based on `main.c`.

ATM, I'm interested in `libmarkdown`, so I only build
* `mktags` as that is required by the intermediate step of the library build
* `mkd2html` as it does not require `main.c`

**Comment by Orc** [comment]
I made a horrible hacky getopt (gethopt) for mkd2html so I could keep the whole-word options + getopt-alike single character options;  let me make a branch that has main.c & makepage.c use that getopt instead of the standard one.

**Comment by mloskot** [comment]
> But in your case just not pulling in the reversion patch will work for now

Without any extra patches, I'm able to build the library and `mkd2html` utility.

In #166 I crafted minimal build configuration, non-intrusive to the current codebase.

**Comment by Orc** [comment]
I made a new branch for you:  gethopt-uber-alles, which replaces the standard sane getopt() with my horrible hacked variant in markdown(8) & makepage(8)

**Comment by mloskot** [comment]
Thanks. I've tried the branch and it works for me.
I submitted #167 which requires changes from `gethopt-uber-alles` to generate complete Discount build with MSVC (tested with VS2015).

**Pull request merged**
