### PR TITLE
Add debug symbols files to make clean.

### PR DESCRIPTION
**Pull request by bradleysepos**
`make clean && make distclean` should now leave a spotless source directory.

### CODE REVIEW

**Comment by Orc** [comment]
I'm not going to merge this, because I didn't want to have it trying to delete .dSYM files if they weren't created.   But I did take your idea and used the existing test for .dSYM files in `configure.inc` to conditionally prefix `-r *.dSYM` to the GENERATED_FILES list for `make distclean`.   Thanks for the merge request poke!

**Comment by bradleysepos** [comment]
No worries at all. However, this doesn't seem to work?

```
$ git log -1 --oneline
2bcdade Merge pull request #131 from koenpunt/mkd_cleanup-from-caller
$ ./configure.sh --mandir=/usr/local/share/man
Configuring for [markdown]
Looking for cpp (/usr/bin/cpp) ok
looking for install (/usr/bin/install)
checking the C compiler (cc) yuck, you're using clang
looking for ar (/usr/bin/ar)
looking for ranlib (/usr/bin/ranlib)
checking for "volatile" keyword (found)
checking for "const" keyword (found)
Checking for "inline" keyword (found)
defining WORD & DWORD scalar types
looking for a reentrant basename (broken)
looking for header pwd.h (found)
looking for the getpwuid function (found)
looking for the srandom function (found)
looking for the bzero function (found)
looking for the random function (found)
looking for the strcasecmp function (found)
looking for the strncasecmp function (found)
looking for the fchdir function (found)
looking for header malloc.h (not found)
looking for find (/usr/bin/find)
looking for "ln -s" (/bin/ln)
looking for ar (/usr/bin/ar)
looking for ranlib (/usr/bin/ranlib)
looking for sed (/usr/bin/sed)
generating Makefile
generating version.c
generating mkdio.h
$ make
cc -Wno-implicit-int -I. -g -I. -c main.c
cc -Wno-implicit-int -I. -g -I. -c pgm_options.c
cc -Wno-implicit-int -I. -g   -c -o mkdio.o mkdio.c
cc -Wno-implicit-int -I. -g   -c -o markdown.o markdown.c
cc -Wno-implicit-int -I. -g   -c -o dumptree.o dumptree.c
cc -Wno-implicit-int -I. -g   -c -o generate.o generate.c
cc -Wno-implicit-int -I. -g   -c -o resource.o resource.c
cc -Wno-implicit-int -I. -g   -c -o docheader.o docheader.c
cc -Wno-implicit-int -I. -g -DVERSION=\"`cat VERSION`\" -c version.c
cc -Wno-implicit-int -I. -g   -c -o toc.o toc.c
cc -Wno-implicit-int -I. -g   -c -o css.o css.c
cc -Wno-implicit-int -I. -g   -c -o xml.o xml.c
cc -Wno-implicit-int -I. -g   -c -o Csio.o Csio.c
cc -Wno-implicit-int -I. -g   -c -o xmlpage.o xmlpage.c
cc -Wno-implicit-int -I. -g   -c -o basename.o basename.c
cc -Wno-implicit-int -I. -g   -c -o emmatch.o emmatch.c
cc -Wno-implicit-int -I. -g   -c -o github_flavoured.o github_flavoured.c
cc -Wno-implicit-int -I. -g   -c -o setup.o setup.c
cc -Wno-implicit-int -I. -g    mktags.c   -o mktags
./mktags > blocktags
cc -Wno-implicit-int -I. -g   -c -o tags.o tags.c
cc -Wno-implicit-int -I. -g   -c -o html5.o html5.c
cc -Wno-implicit-int -I. -g   -c -o flags.o flags.c
./librarian.sh make libmarkdown VERSION mkdio.o markdown.o dumptree.o generate.o resource.o docheader.o version.o toc.o css.o xml.o Csio.o xmlpage.o basename.o emmatch.o github_flavoured.o setup.o tags.o html5.o flags.o 
a - mkdio.o
a - markdown.o
a - dumptree.o
a - generate.o
a - resource.o
a - docheader.o
a - version.o
a - toc.o
a - css.o
a - xml.o
a - Csio.o
a - xmlpage.o
a - basename.o
a - emmatch.o
a - github_flavoured.o
a - setup.o
a - tags.o
a - html5.o
a - flags.o
cc -Wno-implicit-int -I. -g -L. -o markdown main.o pgm_options.o -lmarkdown 
cc -Wno-implicit-int -I. -g   -c -o mkd2html.o mkd2html.c
cc -Wno-implicit-int -I. -g -L. -o mkd2html mkd2html.o -lmarkdown 
cc -Wno-implicit-int -I. -g -L. -o makepage makepage.c pgm_options.o -lmarkdown 
cc -Wno-implicit-int -I. -g   -c -o theme.o theme.c
cc -Wno-implicit-int -I. -g -L. -o theme theme.o pgm_options.o -lmarkdown 
cc -Wno-implicit-int -I. -o echo tools/echo.c
cc -Wno-implicit-int -I. -o cols tools/cols.c
$ make clean && make distclean
rm -f markdown echo cols mkd2html makepage theme *.o
rm -f libmarkdown `./librarian.sh files libmarkdown VERSION`
rm -f markdown echo cols mkd2html makepage theme *.o
rm -f libmarkdown `./librarian.sh files libmarkdown VERSION`
rm -f Makefile version.c mkdio.h config.cmd config.sub config.h config.mak config.log config.md ./mktags ./blocktags ./librarian.sh
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	makepage.dSYM/
	mktags.dSYM/

nothing added to commit but untracked files present (use "git add" to track)
$ 
```

**Comment by Orc** [comment]
Interesting;  which version of osx are you building on?

**Comment by bradleysepos** [comment]
At the moment, 10.10.5 Yosemite with Xcode 7.0.

**Comment by Orc** [comment]
Odd.  That's the same versions I'm using, and after doing a different patch and pushing things around it's acting the same way for me?   I'll investigate further!

**Comment by Orc** [comment]
Ugh.  I effed up the patch;  try it now @ https://github.com/Orc/discount/commit/df6d4d75a2e480c76127e17ebc5353ad6ba1ef58

**Comment by bradleysepos** [comment]
Works here, thanks.

**Pull request closed without merging**
