### PR TITLE
Define strncasecmp as _strnicmp for Visual C++

### PR DESCRIPTION
**Pull request by mloskot**
Simple fix to enable compilation with Visual C++

### CODE REVIEW

**Comment by Orc** [comment]
VC++ doesn't have strncasecmp() or strnicmp().   Yeesh, how standards compliant.

I try to define things like that in config.h and not by putting some OS-specific glue into the code.   As you see, the #ifdefs & #if's I've got in the code are feature switches instead of platform switches.   In the case of VC++ not including not-officially-standard-but-pretty-much-so functions (and I believe that the basis of strncasecmp [strnicmp] came out of Microsoft?) is really what config.h is designed to cover.

**Comment by mloskot** [comment]
VC++ does not implement C99 (unless C99 features are part of C++11/14/17).
VC++ does not implement POSIX either.

AFAICT, neither `mktags.c` nor local headers it includes, do not not include `config.h`.

**Comment by Orc** [comment]
So it doesn't.  (Or didn't;  I just pushed a patch that has mktags #include "config.h")

But that's corrected now, so you should be able to put the proper definition into your copy of config.h and have it get picked up by mktags

**Comment by mloskot** [comment]
That will do, thanks!.

Closing the PR.

**Pull request closed without merging**
