### PR TITLE
Add Travis CI configuration file

### PR DESCRIPTION
**Pull request by mloskot**
* Allows to run CI builds on Travis CI with gcc and clang.
* Runs `make test`.

------

NOTE: Requires to flick the repository switch on for Orc/discount repo in Travis CI https://travis-ci.org/profile/

### CODE REVIEW

**Comment by Orc** [comment]
What is Travis Cl; some sort of automated build/test environment?

**Comment by mloskot** [comment]
Yes, it is.

Travis CI and GitHub are so tightly coupled these days, too easy to assume everyone knows what it is, or AppVeyor too.

**Comment by Orc** [comment]
I'll have to think for a while about merging your patch, because I've already got my own test environment that I use for continuous integration (not visible in SCCS, because I don't check those files in) and I don't like cluttering up the build with things that are machine-specific  (otoh, it is a dotfile, so I can't see it, so if I checked it in I'd never see the file afterwards.)

I'll just keep this open as a reminder if I forget.

**Comment by mloskot** [comment]
> I've already got my own test environment that I use for continuous integration

FYI, these configurations are non-intrusive to any existing build configuration, just two extra files (`.travis.yml` and `appveyor.yml`) but lots of benefits. For example, Travis CI (as well as AppVeyor) can automatically test any submitted pull requests.

**Comment by Orc** [comment]
I've decided to to take this patch, because since I don't use those two ci products there's no guarantee that they'll remain uptodate (this is a problem with the msvc, plan9, and cmake support -- I don't use those platforms or that build system, so those are pretty much guaranteed to be out of date) and I've already got a lot of unmaintained build stuff checked in.

**Comment by Orc** [comment]
It's additional clutter that will fall out of sync or force me to add infrastructure to keep it in sync, which is to me too much intrusion from an online backup of my production sccs.

I (obviously) take advantage of github's bugtracking system, but that doesn't extend tendrils into my source code.   If github had a similarly nonintrusive way of setting up their ci hooks, I'd be willing to use them, but, no, they require being checked into my sccs and that basically guarantees that they'll fall out of date and force me to maintain them so I can keep github as my online backup.

**Comment by Lekensteyn** [comment]
> It's additional clutter that will fall out of sync or force me to add infrastructure to keep it in sync

I think there is a misunderstanding of what "Travis CI" does. While some CI systems automatically modify your source tree after a test, this is not the case with Travis CI. Travis CI just includes extra links in the *web interface* of Github with build and test results, it does not modify the repository in any way.

This is how a [pull request](https://github.com/curl/curl/pull/2682) looks like with various CI systems enabled:
screenshot_20181006_232420

If you then view the commits history, the web interface includes a link to the tests that were executed for that commit (including a pass/fail indicator): https://github.com/curl/curl/commits/master

> If github had a similarly nonintrusive way of setting up their ci hooks, I'd be willing to use them

To be fair, some CI systems do exist that are completely configured in their respective web interfaces (such as AppVeyor). However I never use that and always check in the CI configuration in the source repo since it is effectively a build recipe which allows others (without access to the config via the web interface) to execute the same tests.

Potential workflow:
1. Someone "forks" this repo.
2. They enable Travis for their fork.
3. They push some changes to a branch.
4. They discover that some tests unexpectedly fail and fix up their changes. Goto 3.
5. Once fixed, open a PR in this repo.
6. The maintainer (you) can apply the changes with more confidence.

> they'll fall out of date and force me to maintain them

What do you mean by falling out of date? If the CI indicator shows up as failure, then someone might decide to step up and fix that In the current situation, a patch can break the build or tests and nobody notices until much later.

As Arch Linux uses discount as default markdown program and library, I am willing to contribute some fixes and (cmake) improvements. But without knowing how to test (since there is no CI config that describes how to do it nor documentation that mentions `make test` or other commands), it discourages me as potential contributor and I will spend time somewhere else.

Please give it a try. Travis (and the like) is not snakeoil, it actually improves the software development process and makes developer life much easier.

**Comment by Orc** [comment]
1.  You claimed "does not modify the repository in any way."    I fail to see how _modifying the repository_ does not modify the repository.
2. My build network includes netbsd, freebsd 4.8, and minix 3, none of which are actually supported by travis ci.   I'm not going to publish code that's only known to work on both Redhat & Debian, and I'm **certainly** not going to publish code that I've not had a chance to review.    Holy cow "you are the bottleneck" is a na&iuml;ve simplification of my development & release cycle.
3. Is it a common thing in modern open source development to not verify changes before sending them upstream?    This is an, um, somewhat distressing development in software engineering.

**Comment by mloskot** [comment]
> Is it a common thing in modern open source development to not verify changes before sending them upstream? 

Keywords:
- topic branch
- pull request submission
- pull request checked during builds by CI services
- GitHub pull request checks requirements
- Merge if checks satisfied

**Comment by Lekensteyn** [comment]
> You claimed "does not modify the repository in any way." I fail to see how modifying the repository does not modify the repository.

Sure, obviously you have to check in one configuration file as you would do with documentation. But the CI does not add new commits or build/test artifacts/results to the system which is what I meant.

> I'm not going to publish code that's only known to work on both Redhat & Debian, and I'm certainly not going to publish code that I've not had a chance to review.

Travis CI is intended as enhancement of the workflow, it does not replace it. If you usually do additional checks on odd platforms, then obviously you can still do that. But given that processing markdown is mostly a computational task and not one that depends on the environment and C has some standards, having tests pass on Ubuntu/macOS (the images supported by Travis) should be a reasonable *baseline*.

And aside from the main supported platforms, you can of course let Travis download a NetBSD/FreeBSD/minix/... image and execute it using VM like QEMU, but that adds quite some overhead.

> > > I pull them to my build master, then build and test on my build network.
> >
> > Sorry to put it blunt, but that makes you the bottleneck of the development process. 
> >
> "you are the bottleneck" is a naïve simplification of my development & release cycle.

Sorry for the ambiguity, I meant to refer to the development process [of contributors for individual patches]. They might not have access to the same environment, especially since it is not exactly documented.

> Is it a common thing in modern open source development to not verify changes before sending them upstream?

In general, people try to be nice and act in good faith. For some projects I am involved in, some contributors are not even developers (but network administrators for example). Their contributed changes are valuable, but might need tiny changes. An automated system to help these contributors is key to modern, *collaborative* software development as they might not know how to build the project either with all involved dependencies.

Even for experienced contributors who can test changes locally, their environment might not cover all configurations that should be tested. The CI can then perform *additional* tests to increase confidence.

**Comment by Orc** [comment]
Enough.

The use case for CI, as argued, appears to be so that contributors who want the latest new thing will be reassured that it exists in discount.

It adds nothing except the latest new thing.   That's not even wrong.

**Pull request closed without merging**
