### PR TITLE
Honor CPPFLAGS and LDFLAGS

### PR DESCRIPTION
**Pull request by rbalint**

### CODE REVIEW

**Comment by Orc** [comment]
What is CPPFLAGS?   Flags specific to the preprocessor?

**Comment by rbalint** [comment]
> What is CPPFLAGS? Flags specific to the preprocessor?

Yes, exactly.
There is an automated check in Debian ensuring that they are properly set in the build:
https://salsa.debian.org/rbalint/discount/-/jobs/1061325

**Comment by rbalint** [comment]
I'm preparing the package to be part of Ubuntu main and honoring flags is one important part of ensuring that the shipped binaries are hardened.

**Comment by Orc** [comment]
I know that CPPFLAGS was preprocessor-only flags ~40 years ago, but nobody in my circle of programming friends ever used it because CFLAGS was right there and we thought it was a relic from V6 that would soon be officially obsolete.

Serves me right.

Thank you for the patch!  I've slurped it into the baseline code, and maybe this will light the fire I need to rebuild the TOC generator to better uniquify names and then push out the official v3 base release.

**Pull request merged**
